### ISSUE TITLE
Can we please have the null safety version?

### ISSUE THREAD

**Issue by prakash-indorkar** [sharp3dges/animator_widgets#1]

**Comment by senorprogramador** [comment]
@prakash-indorkar : Good news! There already is a null safety version. ;)

**Comment by prakash-indorkar** [comment]
Hi, sorry.. which version are you referring to as null safe? please help.

**Comment by senorprogramador** [comment]
Hi @prakash-indorkar,

I am sorry, my bad, I thought you where talking about the main animator package...

I will create the null safety version today.

**Comment by senorprogramador** [comment]
Hi @prakash-indorkar,

Just implemented null safety.
You can use `flutter_animator_widgets: ^1.0.2` for null safety from now on.

Sorry for my misunderstanding.

Kind regards.
